import { NextResponse } from 'next/server';
import { createServerClient } from '@supabase/ssr';
import { createClient } from '@supabase/supabase-js';
import { cookies } from 'next/headers';
import { z } from 'zod';
import { generateWithFallback } from '@/lib/llm';

const METERED_TIERS = ['starter', 'pro'];

const ListingDraftSchema = z.object({
  title: z.string().min(1, 'title is required'),
  description: z.string().min(1, 'description is required'),
  tags: z.array(z.string().min(1)).min(1, 'at least one tag is required'),
});

export async function POST(req: Request) {
  try {
    // ── Auth ──────────────────────────────────────────────────────────────
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll: async () => (await cookies()).getAll(),
          setAll: async (cookiesToSet) => {
            const cookieStore = await cookies();
            cookiesToSet.forEach(({ name, value, options }) =>
              cookieStore.set(name, value, options)
            );
          },
        },
      }
    );

    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized. Please sign in.' }, { status: 401 });
    }

    // ── Tier & credits ────────────────────────────────────────────────────
    const { data: shop, error: shopError } = await supabase
      .from('shops')
      .select('id, subscription_tier, ai_credits')
      .eq('id', user.id)
      .single();

    if (shopError || !shop) {
      return NextResponse.json({ error: 'Shop profile not found.' }, { status: 404 });
    }

    const tier = shop.subscription_tier?.toLowerCase() || '';

    if (tier === 'pending' || tier === 'suspended') {
      return NextResponse.json(
        { error: 'Account not active. Please complete payment to unlock AI features.' },
        { status: 403 }
      );
    }

    if (METERED_TIERS.includes(tier) && (!shop.ai_credits || shop.ai_credits <= 0)) {
      return NextResponse.json(
        { error: 'AI credit limit reached. Upgrade to Advanced for unlimited access.', creditsRemaining: 0 },
        { status: 403 }
      );
    }

    // ── Parse body ────────────────────────────────────────────────────────
    const { imageBase64, mimeType } = await req.json();
    if (!imageBase64) {
      return NextResponse.json({ error: 'imageBase64 is required.' }, { status: 400 });
    }

    // ── Listing draft (multi-provider cascade) ────────────────────────────
    const prompt = `You are a luxury e-commerce copywriter for Sanndikaa, a premium boutique marketplace. Analyze this product image carefully and generate compelling listing copy.

Return a JSON object with these fields:
- "title": a concise, premium product title (3-7 words, Title Case)
- "description": a compelling 2-3 sentence product description highlighting quality, materials, and appeal. Write in a confident, luxury tone suitable for a high-end African marketplace.
- "tags": an array of 5 short marketing tags`;

    const { data: parsed, provider } = await generateWithFallback({
      schema: ListingDraftSchema,
      prompt,
      images: [{ data: imageBase64, mimeType: mimeType || 'image/jpeg' }],
      callerName: 'generate-listing',
    });
    console.log(`[generate-listing] Listing generated by ${provider}`);

    // ── Deduct credit for metered tiers ───────────────────────────────────
    if (METERED_TIERS.includes(tier)) {
      const admin = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.SUPABASE_SERVICE_ROLE_KEY!
      );
      await admin.from('shops').update({ ai_credits: shop.ai_credits - 1 }).eq('id', shop.id);
    }

    return NextResponse.json({
      title: parsed.title,
      description: parsed.description,
      tags: parsed.tags || [],
      creditsRemaining: METERED_TIERS.includes(tier) ? Math.max(0, shop.ai_credits - 1) : null,
    });

  } catch (error: any) {
    console.error('[generate-listing] fatal error:', error);

    const msg: string = error?.message || '';
    const isBusy =
      error?.status === 429 || error?.status === 503 ||
      error?.response?.status === 429 || error?.response?.status === 503 ||
      msg.includes('429') || msg.includes('503') ||
      msg.toLowerCase().includes('quota') ||
      msg.toLowerCase().includes('rate limit') ||
      msg.toLowerCase().includes('too many requests') ||
      msg.toLowerCase().includes('overloaded') ||
      msg.toLowerCase().includes('unavailable');

    if (isBusy) {
      return NextResponse.json(
        { error: 'The AI assistant is currently busy. Please try again in a moment or write the description manually.' },
        { status: 429 }
      );
    }

    return NextResponse.json(
      { error: 'Failed to generate listing. Please try again.' },
      { status: 500 }
    );
  }
}
